#!/bin/bash
PROFILE="Default"
while [[ $# > 0 ]]
do
key="$1"
case $key in
    -d|--delete)
        DELETE=YES
    ;;
    -f|--file)
        CHROMEDB="$2"
        shift
    ;;
    -e|--export)
        EXPORT_FILE="$2"
        shift
    ;;
    -p|--profile)
	PROFILE="$2"
	shift
    ;;
    *)
        echo "Usage: rip-chrome-history [OPTIONS]" >/dev/stderr
        echo "    -d|--delete          Delete the database during the rip" >/dev/stderr
        echo "    -e|--export FILE     Export the ripped history into the file (appends)" >/dev/stderr
        echo "    -f|--file DATABASE   Location of the chrome history database [Default: search based on profile]" >/dev/stderr
        echo "    -p|--profile PROFILE The profile within chrome which is ripped [Default: ${PROFILE}]" >/dev/stderr
        exit 1
    ;;
esac
shift
done

if [ -z "$CHROMEDB" ]
then
	if [ -e "${HOME}/.config/chromium/${PROFILE}/History" ]; then
		CHROMEDB="${HOME}/.config/chromium/${PROFILE}/History"
	elif [ -e "${HOME}/.config/google-chrome/${PROFILE}/History" ]; then
		CHROMEDB="${HOME}/.config/google-chrome/${PROFILE}/History"
	elif [ -e "${HOME}/Library/Application Support/Google/Chrome/${PROFILE}/History" ]; then
		CHROMEDB="${HOME}/Library/Application Support/Google/Chrome/${PROFILE}/History"
	fi
fi

DATABASE=$(mktemp 2>/dev/null || mktemp /tmp/TMP.XXXXX)
ISLOCKED=$(sqlite3 "${CHROMEDB}" "SELECT COUNT(*) from urls" 2>&1 1>/dev/null)

if [ ! -f "${CHROMEDB}" ]
then
    echo "Chrome database \"$CHROMEDB\" is missing.  This may be normal behavior if the history is cleared."
    exit 0
fi

if [ "$ISLOCKED" ] 
then
    echo "Locked, using a copy" >/dev/stderr
    cp "${CHROMEDB}" "${DATABASE}.db"
elif [ "$DELETE" ]
then
    echo "Clearing original database" >/dev/stderr
    mv "${CHROMEDB}" "${DATABASE}.db"
else
    cp "${CHROMEDB}" "${DATABASE}.db"
fi

sqlite3 "${DATABASE}.db" "SELECT MAX(visits.visit_time) as visit_time, urls.url as url FROM urls INNER JOIN visits ON urls.id = visits.url GROUP BY urls.id" >> "${DATABASE}.urls"
rm "${DATABASE}.db"
if [ "${EXPORT_FILE}" ];
then
    cat "${DATABASE}.urls" | tee -a "${EXPORT_FILE}"
else
    cat "${DATABASE}.urls"
fi
rm "${DATABASE}.urls" 
